title: P.M.Conception Design
description: Pierre Margerie - Dessinateur CAO en bâtiments
url: https://dorianbayart.github.io/PMC-Design/

sass:
  style: compact # possible values: nested expanded compact compressed
  
